"""Adapter for ``ETF 512400`` — non-ferrous metals ETF snapshot.

Resolution order (set per-call via :class:`SourceConfig`)
--------------------------------------------------------

The ETF 512400 project is a JavaScript app that regenerates
``src/data/liveSnapshot.json`` via ``npm run refresh``. That snapshot is
**committed** to git (the "protected dirty" pattern — see the upstream
README) and therefore IS the public summary by accident: GitHub Actions
can read it directly from a shallow checkout, no separate publishing
step needed.

v0.4 makes this explicit:

1. **Live endpoint** — not implemented (the JS app has no HTTP service
   we control). Reserved for a future Node-side adapter.
2. **Public summary** — ``<source-repo>/src/data/liveSnapshot.json``.
   This is the SAME file as #3 but exposed via the public-summary
   contract so ``--source-mode public`` does not error out. Marked
   ``public_by_default=True`` in the payload metadata.
3. **Cache** — ditto. Aliased to the public summary path. There is no
   separate "cache" location for this source — the JS app's snapshot
   is the single source of truth.

The aliasing means the file is read exactly once regardless of
``--source-mode``, and the synthesis layer keeps reading the same
normalized shape:

* latest price + change %
* NAV daily return
* how many required sources are OK vs. fallback (proxy for trust)
* commodity-driver health summary
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from cn_altdata_brief.adapters.base import AdapterBase, AdapterPayload, AdapterUnavailable
from cn_altdata_brief.config import (
    SOURCE_REPO_DIRS,
    SourceConfig,
    load_source_config,
    public_summary_path,
)

DEFAULT_ROOT = SOURCE_REPO_DIRS["etf_512400"]
DEFAULT_SNAPSHOT = DEFAULT_ROOT / "src" / "data" / "liveSnapshot.json"
DEFAULT_PUBLIC_SUMMARY = public_summary_path("etf_512400")  # equals DEFAULT_SNAPSHOT


class ETF512400Adapter(AdapterBase):
    """Reads the ETF 512400 daily snapshot JSON.

    Source preference is governed by :class:`SourceConfig` (env var
    ``CN_ALTDATA_BRIEF_PREFERENCE`` or ``--source-mode``).

    Unlike the other adapters, ``public`` and ``cache`` resolve to the
    same on-disk path because the upstream JS app commits its snapshot
    directly. The adapter still reports ``source_mode="public"`` when
    public preference is active so the validate command can confirm
    ``--source-mode public`` actually worked end-to-end.
    """

    source_name = "ETF-512400"
    live_url = None  # snapshot is regenerated by the JS app; we just read it.

    def __init__(
        self,
        *,
        snapshot_path: Path | None = None,
        public_summary: Path | None = None,
        allow_live: bool | None = None,
        config: SourceConfig | None = None,
    ) -> None:
        super().__init__(allow_live=allow_live)
        self.snapshot_path = Path(snapshot_path) if snapshot_path else DEFAULT_SNAPSHOT
        # By design, the public summary IS the snapshot. Tests can override
        # either independently, but in production they point at the same path.
        self.public_summary = (
            Path(public_summary) if public_summary
            else (self.snapshot_path if snapshot_path else DEFAULT_PUBLIC_SUMMARY)
        )
        preference = "cache_only" if snapshot_path is not None and public_summary is None else None
        self.config = config if config is not None else load_source_config(
            preference=preference,
            allow_live=allow_live,
        )

    # ------------------------------------------------------------------
    # Resolution dispatch
    # ------------------------------------------------------------------

    def fetch(self) -> AdapterPayload:
        """Public-by-default: same file regardless of preference.

        The ``--source-mode public`` path still raises ``AdapterUnavailable``
        when the snapshot file is missing — that's the validate-time
        signal the JS app needs a refresh.
        """
        cfg = self.config

        # Public summary preferred AND available — the common path.
        if cfg.prefer_public and self.public_summary.exists():
            return self._load_from_public_summary()

        # public_only and the file is missing: fail fast with a clear note.
        if not cfg.allow_cache:
            raise AdapterUnavailable(
                f"ETF 512400 liveSnapshot.json missing at {self.public_summary}; "
                "this source is public-by-default — run `npm run refresh` "
                "upstream so the snapshot gets regenerated (and committed)."
            )

        return self.fetch_cached()

    # ------------------------------------------------------------------
    # Implementations
    # ------------------------------------------------------------------

    def fetch_cached(self) -> AdapterPayload:
        if not self.snapshot_path.exists():
            raise AdapterUnavailable(
                f"liveSnapshot.json missing at {self.snapshot_path}; "
                "run `npm run refresh` in the ETF 512400 project first"
            )
        payload = self.read_json(self.snapshot_path)
        data = _normalize_snapshot(payload)
        data["source_mode"] = "cache"
        data["public_by_default"] = True
        return AdapterPayload(
            source=self.source_name,
            fetched_at=self.now_iso(),
            cache_path=self.snapshot_path,
            live=False,
            data=data,
        )

    def _load_from_public_summary(
        self, *, summary_path: Path | None = None
    ) -> AdapterPayload:
        """Alias of :meth:`fetch_cached` — but reports ``source_mode="public"``.

        The on-disk artifact is the same file. We re-mark the source_mode
        so the validate layer can distinguish "we honored
        ``--source-mode public``" from "we fell back to cache".

        The ``public_by_default`` flag is set on the payload metadata so
        downstream sections / scripts that audit "which sources have a
        proper public summary path" don't accidentally treat ETF 512400
        as missing a public path.
        """
        path = summary_path if summary_path is not None else self.public_summary
        if not path.exists():
            raise AdapterUnavailable(
                f"ETF 512400 liveSnapshot.json missing at {path}; "
                "public-by-default but the upstream commit has not landed."
            )
        payload = self.read_json(path)
        data = _normalize_snapshot(payload)
        data["source_mode"] = "public"
        data["public_summary_path"] = str(path)
        data["public_by_default"] = True
        return AdapterPayload(
            source=self.source_name,
            fetched_at=self.now_iso(),
            cache_path=path,
            live=False,
            data=data,
        )


def _normalize_snapshot(payload: dict[str, Any]) -> dict[str, Any]:
    """Pluck the fields the ETF-flow section needs."""
    meta = payload.get("meta", {}) or {}
    quote = payload.get("quote", {}) or {}
    nav = payload.get("nav", {}) or {}
    nav_trend = payload.get("navTrend", []) or []
    sources = meta.get("sourceHealth", []) or []

    ok_count = sum(1 for s in sources if s.get("ok"))
    required = [s for s in sources if s.get("required")]
    required_ok = sum(1 for s in required if s.get("ok"))
    fallback_count = sum(1 for s in sources if s.get("fallback"))

    # Last 5 trading days from navTrend (tail end is most recent).
    recent_nav = nav_trend[-5:] if nav_trend else []

    commodity_drivers = (
        next(
            (s for s in sources if s.get("id") == "commodityDrivers"),
            {},
        )
        or {}
    )

    return {
        "generated_at": meta.get("generatedAt"),
        "mode": meta.get("mode"),
        "code": quote.get("code"),
        "name": quote.get("name"),
        "trade_date": quote.get("tradeDate"),
        "price": quote.get("price"),
        "change_percent": quote.get("changePercent"),
        "amount_cny": quote.get("amountCny"),
        "turnover_rate": quote.get("turnoverRate"),
        "nav": {
            "date": nav.get("date"),
            "unit": nav.get("unit"),
            "daily_return": nav.get("dailyReturn"),
            "accumulated": nav.get("accumulated"),
        },
        "recent_nav": recent_nav,
        "source_health": {
            "total": len(sources),
            "ok": ok_count,
            "required_total": len(required),
            "required_ok": required_ok,
            "fallback": fallback_count,
            "verdict": _health_verdict(required_ok, len(required), fallback_count),
        },
        "commodity_drivers": {
            "ok_count": int(commodity_drivers.get("okCount", 0) or 0),
            "total": int(commodity_drivers.get("total", 0) or 0),
            "fallback_count": int(commodity_drivers.get("fallbackCount", 0) or 0),
            "ok": bool(commodity_drivers.get("ok", False)),
        },
    }


def _health_verdict(required_ok: int, required_total: int, fallback_count: int) -> str:
    """Mirror the source-health contract used in the JS app."""
    if required_total == 0:
        return "未知"
    if required_ok < required_total:
        return "降级"
    if fallback_count > 0:
        return "可用 (含 proxy)"
    return "良好"
