"""Adapter for ``ETF 512400`` — non-ferrous metals ETF snapshot."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from cn_altdata_brief.adapters.base import AdapterBase, AdapterPayload, AdapterUnavailable

DEFAULT_ROOT = Path("/Users/leonardodon/ETF 512400")
DEFAULT_SNAPSHOT = DEFAULT_ROOT / "src" / "data" / "liveSnapshot.json"


class ETF512400Adapter(AdapterBase):
    """Reads the ETF 512400 daily snapshot JSON.

    The snapshot carries quote, NAV trend, source-health board, and
    commodity drivers. The brief's *ETF flow* section needs:

    * latest price + change %
    * NAV daily return
    * how many required sources are OK vs. fallback (proxy for trust)
    * commodity-driver health summary
    """

    source_name = "ETF-512400"
    live_url = None  # snapshot is regenerated by the JS app; we just read it.

    def __init__(
        self,
        *,
        snapshot_path: Path | None = None,
        allow_live: bool | None = None,
    ) -> None:
        super().__init__(allow_live=allow_live)
        self.snapshot_path = Path(snapshot_path) if snapshot_path else DEFAULT_SNAPSHOT

    # ------------------------------------------------------------------

    def fetch_cached(self) -> AdapterPayload:
        if not self.snapshot_path.exists():
            raise AdapterUnavailable(
                f"liveSnapshot.json missing at {self.snapshot_path}; "
                "run `npm run refresh` in the ETF 512400 project first"
            )
        payload = self.read_json(self.snapshot_path)
        return AdapterPayload(
            source=self.source_name,
            fetched_at=self.now_iso(),
            cache_path=self.snapshot_path,
            live=False,
            data=_normalize_snapshot(payload),
        )


def _normalize_snapshot(payload: dict[str, Any]) -> dict[str, Any]:
    """Pluck the fields the ETF-flow section needs."""
    meta = payload.get("meta", {}) or {}
    quote = payload.get("quote", {}) or {}
    nav = payload.get("nav", {}) or {}
    nav_trend = payload.get("navTrend", []) or []
    sources = meta.get("sourceHealth", []) or []

    ok_count = sum(1 for s in sources if s.get("ok"))
    required = [s for s in sources if s.get("required")]
    required_ok = sum(1 for s in required if s.get("ok"))
    fallback_count = sum(1 for s in sources if s.get("fallback"))

    # Last 5 trading days from navTrend (tail end is most recent).
    recent_nav = nav_trend[-5:] if nav_trend else []

    commodity_drivers = (
        next(
            (s for s in sources if s.get("id") == "commodityDrivers"),
            {},
        )
        or {}
    )

    return {
        "generated_at": meta.get("generatedAt"),
        "mode": meta.get("mode"),
        "code": quote.get("code"),
        "name": quote.get("name"),
        "trade_date": quote.get("tradeDate"),
        "price": quote.get("price"),
        "change_percent": quote.get("changePercent"),
        "amount_cny": quote.get("amountCny"),
        "turnover_rate": quote.get("turnoverRate"),
        "nav": {
            "date": nav.get("date"),
            "unit": nav.get("unit"),
            "daily_return": nav.get("dailyReturn"),
            "accumulated": nav.get("accumulated"),
        },
        "recent_nav": recent_nav,
        "source_health": {
            "total": len(sources),
            "ok": ok_count,
            "required_total": len(required),
            "required_ok": required_ok,
            "fallback": fallback_count,
            "verdict": _health_verdict(required_ok, len(required), fallback_count),
        },
        "commodity_drivers": {
            "ok_count": int(commodity_drivers.get("okCount", 0) or 0),
            "total": int(commodity_drivers.get("total", 0) or 0),
            "fallback_count": int(commodity_drivers.get("fallbackCount", 0) or 0),
            "ok": bool(commodity_drivers.get("ok", False)),
        },
    }


def _health_verdict(required_ok: int, required_total: int, fallback_count: int) -> str:
    """Mirror the source-health contract used in the JS app."""
    if required_total == 0:
        return "未知"
    if required_ok < required_total:
        return "降级"
    if fallback_count > 0:
        return "可用 (含 proxy)"
    return "良好"
