"""本日观察 — 2-3 sentence cross-cutting takeaway, deterministic rules."""

from __future__ import annotations

from typing import Any

from cn_altdata_brief.adapters.base import AdapterPayload


def synthesize_observation(
    super_payload: AdapterPayload | None,
    quant_payload: AdapterPayload | None,
    index_payload: AdapterPayload | None,
    etf_payload: AdapterPayload | None,
) -> dict[str, Any]:
    """Cross-section observation: rule-based, NOT an LLM call.

    The rules combine signals from up to 4 sources to produce two or
    three short Chinese sentences. Each sentence is generated by a
    standalone predicate function so they can be unit-tested.
    """
    sentences: list[str] = []
    sources: list[str] = []

    if super_payload is not None:
        sources.append(super_payload.cache_label)
        s = _policy_skew_sentence(super_payload)
        if s:
            sentences.append(s)
        s = _inventory_dispersion_sentence(super_payload)
        if s:
            sentences.append(s)

    if etf_payload is not None:
        sources.append(etf_payload.cache_label)
        s = _etf_nav_sentence(etf_payload)
        if s:
            sentences.append(s)

    if quant_payload is not None and not any("行业" in t for t in sentences):
        sources.append(quant_payload.cache_label)
        s = _industry_heat_sentence(quant_payload)
        if s:
            sentences.append(s)

    if index_payload is not None:
        sources.append(index_payload.cache_label)
        s = _verdict_freshness_sentence(index_payload)
        if s:
            sentences.append(s)

    if not sentences:
        sentences = ["_数据缺失_：所有上游均未返回有效信号，今日无可生成观察。"]

    return {
        "available": bool(sentences and not sentences[0].startswith("_数据缺失_")),
        "title": "本日观察",
        "sentences": sentences[:3],
        "sources": sources,
    }


# ---- predicate helpers (each returns one sentence or None) ----------


def _policy_skew_sentence(payload: AdapterPayload) -> str | None:
    policy = payload.data.get("policy_radar", {}) or {}
    ranked = policy.get("industry_signals", []) or []
    if not ranked:
        return None
    top = ranked[0]
    impact = float(top.get("avg_impact", 0.0) or 0.0)
    if abs(impact) < 0.05:
        return None
    direction = "偏空" if impact < 0 else "偏多"
    return (
        f"政策口径继续向 **{top['industry']}** 倾斜（{direction}，"
        f"avg_impact={impact:+.3f}，mentions={top.get('mentions', 0)}），"
        f"是当前 policy_radar 的最强信号源。"
    )


def _inventory_dispersion_sentence(payload: AdapterPayload) -> str | None:
    macro = payload.data.get("macro_hf", {}) or {}
    metals = macro.get("metals", []) or []
    if len(metals) < 2:
        return None
    changes = [float(m.get("price_change_pct", 0.0) or 0.0) for m in metals]
    spread = max(changes) - min(changes)
    if spread < 0.5:
        return "金属库存价格变化分歧度较低（spread < 0.5%），上下游分化暂未发酵。"
    leader = max(metals, key=lambda m: float(m.get("price_change_pct", 0.0) or 0.0))
    laggard = min(metals, key=lambda m: float(m.get("price_change_pct", 0.0) or 0.0))
    return (
        f"金属内部分化加大：**{leader.get('name_cn')}** 与 **{laggard.get('name_cn')}** "
        f"周价差 {spread:.2f}%，建议关注配对交易窗口。"
    )


def _etf_nav_sentence(payload: AdapterPayload) -> str | None:
    nav = payload.data.get("nav", {}) or {}
    daily = nav.get("daily_return")
    if daily is None:
        return None
    pct = float(daily) * 100
    if abs(pct) < 0.5:
        return None
    direction = "上涨" if pct > 0 else "下跌"
    health = payload.data.get("source_health", {}) or {}
    return (
        f"ETF 512400 日内 NAV {direction} {abs(pct):.2f}%，"
        f"数据源评级 **{health.get('verdict', '未知')}**，可在尾盘前确认抢权或离场。"
    )


def _industry_heat_sentence(payload: AdapterPayload) -> str | None:
    rows = payload.data.get("industries", []) or []
    if not rows:
        return None
    top = rows[0]
    return (
        f"行业热度榜首是 **{top['industry']}** "
        f"(heat={float(top.get('heat_score', 0)):.3f})，"
        f"配合 policy 信号 {top.get('policy_signal')}，关注资金外溢方向。"
    )


def _verdict_freshness_sentence(payload: AdapterPayload) -> str | None:
    pap = payload.data.get("pap_changes", []) or []
    if pap:
        return (
            f"index-inclusion-research PAP 比对发现 {len(pap)} 条假说裁决发生迁移，"
            "提示研究框架今日有新一致性事件。"
        )
    verdicts = payload.data.get("verdicts", []) or []
    if not verdicts:
        return None
    supported = sum(1 for v in verdicts if v.get("verdict") == "支持")
    total = len(verdicts)
    return (
        f"index-inclusion-research 7 条 CMA 裁决保持稳定，{supported}/{total} 为「支持」，"
        "今日无机制翻盘。"
    )
